[package]
name = "tikv-importer"
version = "3.0.2"
authors = ["The TiKV Authors"]
description = "Tool to help ingesting large number of KV pairs into TiKV cluster"
license = "Apache-2.0"
repository = "https://github.com/tikv/importer/"
edition = "2018"
publish = false

[lib]
name = "tikv_importer"

[[bin]]
name = "tikv-importer"

[[test]]
name = "integrations"
path = "tests/integrations/import/mod.rs"

[dependencies]
backup = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
clap = "2.33"
cmd = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
crc = "1.8"
crossbeam = "0.5"
engine = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
futures = "0.1"
futures-cpupool = "0.1"
grpcio = { version = "0.5.0-alpha.3", features = [ "openssl-vendored" ] }
hex = "0.3"
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "backup2" }
lazy_static = "1.3"
log_wrappers = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
prometheus = { version = "0.4", default-features = false, features = ["nightly", "push", "process"] }
quick-error = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slog = { version = "2.4", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
tikv = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
tikv_util = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
tidb_query = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
pd_client = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }
uuid = { version = "0.6", features = [ "serde", "v4" ] }
tipb = { git = "https://github.com/pingcap/tipb.git" }
toml = "0.4"

[dev-dependencies]
tempdir = "0.3"
rand = "0.6"
test_util = { git = "https://github.com/tikv/tikv.git", branch = "backup2" }

[replace]
"https:/github.com/pingcap/kvproto.git#kvproto:0.0.2" = { git = "https://github.com/pingcap/kvproto.git", branch = "backup2" }
"protobuf:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }
"protobuf-codegen:2.8.0" = { git = "https://github.com/nrc/rust-protobuf", branch = "v2.8" }
"raft:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master" }
"raft-proto:0.6.0-alpha" = { git = "https://github.com/pingcap/raft-rs", branch = "master" }

[features]
default = ['tikv/default']
tcmalloc = ['tikv/tcmalloc']
jemalloc = ['tikv/jemalloc']
portable = ['tikv/portable']
sse = ['tikv/sse']
mem-profiling = ['tikv/mem-profiling']

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
