[package]
name = "tikv-importer"
<<<<<<< HEAD
version = "4.0.0-alpha"
=======
version = "3.0.2"
>>>>>>> origin/master
authors = ["The TiKV Authors"]
description = "Tool to help ingesting large number of KV pairs into TiKV cluster"
license = "Apache-2.0"
repository = "https://github.com/tikv/importer/"
edition = "2018"
publish = false

[lib]
name = "tikv_importer"

[[bin]]
name = "tikv-importer"

[[test]]
name = "integrations"
path = "tests/integrations/import/mod.rs"

[dependencies]
clap = "2.33"
crc = "1.8"
crossbeam = "0.5"
<<<<<<< HEAD
engine = { git = "https://github.com/tikv/tikv.git", rev = "c1bbc2c4" }
=======
engine = { version = "0.0.1", git = "https://github.com/tikv/tikv.git", tag = "v3.0.1" }
>>>>>>> origin/master
futures = "0.1"
futures-cpupool = "0.1"
grpcio = "0.5.0-alpha.3"
kvproto = { version = "0.0.2", git = "https://github.com/pingcap/kvproto.git", branch = "master" }
lazy_static = "1.3"
<<<<<<< HEAD
log_wrappers = { version = "0.0.1", git = "https://github.com/tikv/tikv.git", rev = "c1bbc2c4" }
=======
log_wrappers = { version = "0.0.1", git = "https://github.com/tikv/tikv.git", tag = "v3.0.1" }
>>>>>>> origin/master
prometheus = { version = "0.4", default-features = false, features = ["nightly", "push", "process"] }
quick-error = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slog = { version = "2.4", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
<<<<<<< HEAD
tikv = { git = "https://github.com/tikv/tikv.git", rev = "c1bbc2c4" }
tikv_util = { git = "https://github.com/tikv/tikv.git", rev = "c1bbc2c4" }
=======
tikv = { version = "3.0.1", git = "https://github.com/tikv/tikv.git", tag = "v3.0.1" }
tikv_util = { version = "0.1", git = "https://github.com/tikv/tikv.git", tag = "v3.0.1" }
>>>>>>> origin/master
uuid = { version = "0.6", features = [ "serde", "v4" ] }
tipb = { git = "https://github.com/pingcap/tipb.git" }
toml = "0.4"

[dev-dependencies]
tempdir = "0.3"
rand = "0.6"
<<<<<<< HEAD
test_util = { git = "https://github.com/tikv/tikv.git", rev = "c1bbc2c4" }
=======
test_util = { version = "0.0.1", git = "https://github.com/tikv/tikv.git", tag = "v3.0.1" }
>>>>>>> origin/master

[features]
default = ['tikv/default']
tcmalloc = ['tikv/tcmalloc']
jemalloc = ['tikv/jemalloc']
portable = ['tikv/portable']
sse = ['tikv/sse']
mem-profiling = ['tikv/mem-profiling']
profiling = ['tikv/profiling']

[patch.'https://github.com/pingcap/kvproto.git']
kvproto = { path = '/Users/lance/Projects/go/src/github.com/pingcap/kvproto' }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
